// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jabyjklpquqmqqrierjx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImphYnlqa2xwcXVxbXFxcmllcmp4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3NjEyMTAsImV4cCI6MjA1NzMzNzIxMH0.MgfPCMy72Uzu4EPv6pz1tJlzjrSHq3TNdQcrqMgZq6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);